apiVersion: v1
kind: Service
metadata:
  name: devops-assessment-service
spec:
  selector:
    app: devops-assessment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

